# Generated by Django 3.1.2 on 2020-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=100)),
                ('class_id', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('secprice', models.FloatField()),
                ('condition', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('goods_num', models.IntegerField()),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('mes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mes_type', models.IntegerField(default=1)),
                ('user_name', models.CharField(max_length=50)),
                ('mes_content', models.CharField(max_length=200)),
                ('res_id', models.IntegerField(null=True)),
                ('goods_id', models.IntegerField(default=0)),
                ('mes_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('rec_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('order_time', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('state', models.CharField(max_length=20)),
                ('send', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.IntegerField()),
                ('order_id', models.IntegerField(default=0)),
                ('goods_id', models.IntegerField(default=0)),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_price', models.FloatField()),
                ('goods_num', models.IntegerField()),
                ('goods_cost', models.FloatField()),
            ],
            options={
                'db_table': 'Orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Type_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(default=0)),
                ('class_name', models.CharField(max_length=50)),
                ('father_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Type_id',
            },
        ),
    ]
