# Generated by Django 3.1.2 on 2020-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='favorites',
            name='goods_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='class_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='goods_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='goods_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type_id',
            name='class_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type_id',
            name='father_id',
            field=models.IntegerField(default=0),
        ),
    ]
