# Generated by Django 3.1.3 on 2020-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201102_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='https://i.loli.net/2020/11/08/KnofmQWD15BxcMu.jpg', upload_to='', verbose_name='头像'),
        ),
    ]
