# Generated by Django 3.1.2 on 2020-10-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('secprice', models.FloatField()),
                ('condition', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('goods_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=20)),
                ('seller_name', models.CharField(max_length=20)),
                ('rec_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('order_time', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('state', models.CharField(max_length=20)),
                ('send', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('father_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=100, null=True)),
                ('user_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_price', models.FloatField()),
                ('goods_num', models.IntegerField()),
                ('goods_cost', models.FloatField()),
                ('goods_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuptFish.goods')),
                ('order_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BuptFish.order')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('mes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mes_content', models.CharField(max_length=200)),
                ('re_content', models.CharField(max_length=200)),
                ('mes_time', models.DateTimeField()),
                ('goods_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BuptFish.goods')),
                ('user_name', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='BuptFish.user')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BuptFish.type_id'),
        ),
    ]
