# Generated by Django 3.1.2 on 2020-10-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuptFish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='re_content',
        ),
        migrations.AddField(
            model_name='messages',
            name='mes_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='messages',
            name='res_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuptFish.goods')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuptFish.user')),
            ],
        ),
    ]
